### ISSUE TITLE
No boot and a warning after running the program

### ISSUE THREAD

**Issue by waterflow80** [Jihadmimouni/GL1TCH_OS#2]
### Reproducing The Behavior:
- cloned the project locally
- installed all the required tools mentioned in #1 **(except for the WWC compiler and the Bochs debugger** )
- run `make` in the root directory
- run `./run.sh`

### Output:
I got the following warning:

```shell
WARNING: Image format was not specified for 'build/main_floppy.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```
and the emulator shows the following:

![Screenshot from 2023-11-29 00-12-02](https://github.com/Jihadmimouni/GL1TCH_OS/assets/82417779/84e8cf8b-6039-4139-9190-d45f32db9c33)

Is this a normal behavior ?

**Comment by Jihadmimouni** [comment]
Thanks for reaching out! The behavior you're noticing is normal because the OS is in the early stages of  development.
